# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }

# ProofWork TaskFactory - deploys TaskVerifier child contracts and holds their
# GEN reward escrow. This is the contract deployed/hardcoded per network;
# TaskVerifier is never deployed directly.
#
# TASK_VERIFIER_CODE_B64 below is generated from task_verifier.py - do not
# hand-edit it. Run `python3 contracts/generate_factory.py` after changing
# task_verifier.py to regenerate it.

from genlayer import *

from datetime import datetime, timezone
import base64

RELEASE_WINDOW_SECONDS = 86400  # 24h dispute window before escrow auto-releases

TASK_VERIFIER_CODE_B64 = "IyB7ICJEZXBlbmRzIjogInB5LWdlbmxheWVyOjFqYjQ1YWE4eW5oMmE5Yzl4bjNiN3FxaDhzbTVxOTNod2ZwN2pxbXdzZmhoOGpwejA5aDYiIH0KCiMgQUktVmVyaWZpZWQgVGFzayBDb21wbGV0aW9uIC0gR2VuTGF5ZXIgSW50ZWxsaWdlbnQgQ29udHJhY3QKIyBEZXBsb3llZCBhcyBhIGNoaWxkIG9mIFRhc2tGYWN0b3J5IChzZWUgdGFza19mYWN0b3J5LnB5KSAtIG5vdCBkZXBsb3llZCBkaXJlY3RseS4KCmZyb20gZ2VubGF5ZXIgaW1wb3J0ICoKCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lLCB0aW1lem9uZQppbXBvcnQganNvbgoKRVJST1JfRVhQRUNURUQgPSAiW0VYUEVDVEVEXSIgICMgYnVzaW5lc3MgbG9naWMgLSBkZXRlcm1pbmlzdGljLCBleGFjdCBtYXRjaApFUlJPUl9FWFRFUk5BTCA9ICJbRVhURVJOQUxdIiAgIyBleHRlcm5hbCBBUEkgNHh4IC0gZGV0ZXJtaW5pc3RpYywgZXhhY3QgbWF0Y2gKRVJST1JfVFJBTlNJRU5UID0gIltUUkFOU0lFTlRdIiAgIyBuZXR3b3JrLzV4eCAtIG5vbi1kZXRlcm1pbmlzdGljLCBhZ3JlZSBpZiBib3RoIHRyYW5zaWVudApFUlJPUl9MTE0gPSAiW0xMTV9FUlJPUl0iICAjIExMTSBtaXNiZWhhdmlvciAtIGFsd2F5cyBkaXNhZ3JlZSwgZm9yY2Ugcm90YXRpb24KCgpjbGFzcyBUYXNrVmVyaWZpZXIoZ2wuQ29udHJhY3QpOgogICAgY3JlYXRvcjogc3RyCiAgICBmYWN0b3J5OiBzdHIKICAgIHRpdGxlOiBzdHIKICAgIGNhdGVnb3J5OiBzdHIKICAgIGNhdGVnb3J5X290aGVyOiBzdHIKICAgIHByaW9yaXR5OiBzdHIKICAgIGVzdGltYXRlZF9lZmZvcnQ6IHN0cgogICAgZGVzY3JpcHRpb246IHN0cgogICAgY3JpdGVyaWE6IHN0cgogICAgc3VibWlzc2lvbl9mb3JtYXQ6IHN0cgogICAgc3VibWlzc2lvbl9mb3JtYXRfb3RoZXI6IHN0cgogICAgcmV3YXJkX2Ftb3VudDogdTI1NgogICAgZGVhZGxpbmU6IHUyNTYgICMgdW5peCB0aW1lc3RhbXA7IHdvcmtlciBtdXN0IHN1Ym1pdCBiZWZvcmUgdGhpcwogICAgd29ya2VyOiBzdHIKICAgIHN1Ym1pc3Npb25fdXJsOiBzdHIKICAgIHN1Ym1pc3Npb25fbm90ZTogc3RyCiAgICBzdGF0dXM6IHN0ciAgIyAib3BlbiIsICJjbGFpbWVkIiwgInN1Ym1pdHRlZCIsICJ2ZXJpZmllZCIsICJyZWplY3RlZCIsICJkaXNwdXRlZCIKICAgIHZlcmlmaWNhdGlvbl9yZXN1bHQ6IHN0cgogICAgZGlzcHV0ZV9jb3VudDogdTI1NgogICAgZGlzcHV0ZV9yZWFzb246IHN0cgogICAgY3JlYXRlZF9hdDogdTI1NgogICAgdmVyaWZpZWRfYXQ6IHUyNTYgICMgc2V0IHdoZW4gc3RhdHVzIGZpcnN0IGJlY29tZXMgdmVyaWZpZWQvcmVqZWN0ZWQ7IGVzY3JvdyByZWxlYXNlIHdpbmRvdyBzdGFydHMgaGVyZQoKICAgIGRlZiBfX2luaXRfXygKICAgICAgICBzZWxmLAogICAgICAgIGNyZWF0b3I6IHN0ciwKICAgICAgICBmYWN0b3J5OiBzdHIsCiAgICAgICAgdGl0bGU6IHN0ciwKICAgICAgICBjYXRlZ29yeTogc3RyLAogICAgICAgIGNhdGVnb3J5X290aGVyOiBzdHIsCiAgICAgICAgcHJpb3JpdHk6IHN0ciwKICAgICAgICBlc3RpbWF0ZWRfZWZmb3J0OiBzdHIsCiAgICAgICAgZGVzY3JpcHRpb246IHN0ciwKICAgICAgICBjcml0ZXJpYTogc3RyLAogICAgICAgIHN1Ym1pc3Npb25fZm9ybWF0OiBzdHIsCiAgICAgICAgc3VibWlzc2lvbl9mb3JtYXRfb3RoZXI6IHN0ciwKICAgICAgICByZXdhcmRfYW1vdW50OiBpbnQsCiAgICAgICAgZGVhZGxpbmU6IGludCwKICAgICk6CiAgICAgICAgbm93ID0gaW50KGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLnRpbWVzdGFtcCgpKQogICAgICAgIGFzc2VydCBkZWFkbGluZSA+IG5vdywgIkRlYWRsaW5lIG11c3QgYmUgaW4gdGhlIGZ1dHVyZSIKICAgICAgICBzZWxmLmNyZWF0b3IgPSBjcmVhdG9yCiAgICAgICAgc2VsZi5mYWN0b3J5ID0gZmFjdG9yeQogICAgICAgIHNlbGYudGl0bGUgPSB0aXRsZQogICAgICAgIHNlbGYuY2F0ZWdvcnkgPSBjYXRlZ29yeQogICAgICAgIHNlbGYuY2F0ZWdvcnlfb3RoZXIgPSBjYXRlZ29yeV9vdGhlcgogICAgICAgIHNlbGYucHJpb3JpdHkgPSBwcmlvcml0eQogICAgICAgIHNlbGYuZXN0aW1hdGVkX2VmZm9ydCA9IGVzdGltYXRlZF9lZmZvcnQKICAgICAgICBzZWxmLmRlc2NyaXB0aW9uID0gZGVzY3JpcHRpb24KICAgICAgICBzZWxmLmNyaXRlcmlhID0gY3JpdGVyaWEKICAgICAgICBzZWxmLnN1Ym1pc3Npb25fZm9ybWF0ID0gc3VibWlzc2lvbl9mb3JtYXQKICAgICAgICBzZWxmLnN1Ym1pc3Npb25fZm9ybWF0X290aGVyID0gc3VibWlzc2lvbl9mb3JtYXRfb3RoZXIKICAgICAgICBzZWxmLnJld2FyZF9hbW91bnQgPSByZXdhcmRfYW1vdW50CiAgICAgICAgc2VsZi5kZWFkbGluZSA9IGRlYWRsaW5lCiAgICAgICAgc2VsZi53b3JrZXIgPSAiIgogICAgICAgIHNlbGYuc3VibWlzc2lvbl91cmwgPSAiIgogICAgICAgIHNlbGYuc3VibWlzc2lvbl9ub3RlID0gIiIKICAgICAgICBzZWxmLnN0YXR1cyA9ICJvcGVuIgogICAgICAgIHNlbGYudmVyaWZpY2F0aW9uX3Jlc3VsdCA9ICIiCiAgICAgICAgc2VsZi5kaXNwdXRlX2NvdW50ID0gMAogICAgICAgIHNlbGYuZGlzcHV0ZV9yZWFzb24gPSAiIgogICAgICAgIHNlbGYuY3JlYXRlZF9hdCA9IG5vdwogICAgICAgIHNlbGYudmVyaWZpZWRfYXQgPSAwCgogICAgQGdsLnB1YmxpYy53cml0ZQogICAgZGVmIGNsYWltX3Rhc2soc2VsZikgLT4gTm9uZToKICAgICAgICBjYWxsZXIgPSBzdHIoZ2wubWVzc2FnZS5zZW5kZXJfYWRkcmVzcykKICAgICAgICBub3cgPSBpbnQoZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykudGltZXN0YW1wKCkpCiAgICAgICAgYXNzZXJ0IHNlbGYuc3RhdHVzID09ICJvcGVuIiwgIlRhc2sgaXMgbm90IG9wZW4iCiAgICAgICAgYXNzZXJ0IGNhbGxlciAhPSBzZWxmLmNyZWF0b3IsICJDcmVhdG9yIGNhbm5vdCBjbGFpbSBvd24gdGFzayIKICAgICAgICBhc3NlcnQgbm93IDw9IHNlbGYuZGVhZGxpbmUsICJUYXNrIGRlYWRsaW5lIGhhcyBwYXNzZWQiCiAgICAgICAgc2VsZi53b3JrZXIgPSBjYWxsZXIKICAgICAgICBzZWxmLnN0YXR1cyA9ICJjbGFpbWVkIgoKICAgIEBnbC5wdWJsaWMud3JpdGUKICAgIGRlZiBzdWJtaXRfd29yayhzZWxmLCBldmlkZW5jZV91cmw6IHN0ciwgc3VibWlzc2lvbl9ub3RlOiBzdHIpIC0+IE5vbmU6CiAgICAgICAgY2FsbGVyID0gc3RyKGdsLm1lc3NhZ2Uuc2VuZGVyX2FkZHJlc3MpCiAgICAgICAgbm93ID0gaW50KGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLnRpbWVzdGFtcCgpKQogICAgICAgIGFzc2VydCBjYWxsZXIgPT0gc2VsZi53b3JrZXIsICJPbmx5IGFzc2lnbmVkIHdvcmtlciBjYW4gc3VibWl0IgogICAgICAgIGFzc2VydCBzZWxmLnN0YXR1cyA9PSAiY2xhaW1lZCIsICJUYXNrIG11c3QgYmUgY2xhaW1lZCBmaXJzdCIKICAgICAgICBhc3NlcnQgbm93IDw9IHNlbGYuZGVhZGxpbmUsICJUYXNrIGRlYWRsaW5lIGhhcyBwYXNzZWQiCgogICAgICAgIHVybF9sb3dlciA9IGV2aWRlbmNlX3VybC5sb3dlcigpLnN0cmlwKCkKICAgICAgICBhc3NlcnQgdXJsX2xvd2VyLnN0YXJ0c3dpdGgoImh0dHA6Ly8iKSBvciB1cmxfbG93ZXIuc3RhcnRzd2l0aCgiaHR0cHM6Ly8iKSwgXAogICAgICAgICAgICAiRXZpZGVuY2UgbXVzdCBiZSBhIHZhbGlkIFVSTCIKICAgICAgICBleHBlY3RlZF9mb3JtYXQgPSBzZWxmLnN1Ym1pc3Npb25fZm9ybWF0CiAgICAgICAgaWYgZXhwZWN0ZWRfZm9ybWF0ID09ICJHaXRIdWIgUmVwb3NpdG9yeSI6CiAgICAgICAgICAgIGFzc2VydCAiZ2l0aHViLmNvbSIgaW4gdXJsX2xvd2VyLCBcCiAgICAgICAgICAgICAgICAiVGhpcyB0YXNrIGV4cGVjdHMgYSBHaXRIdWIgUmVwb3NpdG9yeSBVUkwgKGdpdGh1Yi5jb20pIgoKICAgICAgICBzZWxmLnN1Ym1pc3Npb25fdXJsID0gZXZpZGVuY2VfdXJsCiAgICAgICAgc2VsZi5zdWJtaXNzaW9uX25vdGUgPSBzdWJtaXNzaW9uX25vdGUKICAgICAgICBzZWxmLnN0YXR1cyA9ICJzdWJtaXR0ZWQiCiAgICAgICAgIyBFdmlkZW5jZSBpcyBub3cgbG9ja2VkIGluLiBBSSB2ZXJpZmljYXRpb24gbXVzdCBiZSB0cmlnZ2VyZWQgc2VwYXJhdGVseQogICAgICAgICMgdmlhIHJlcXVlc3RfdmVyaWZpY2F0aW9uKCkgYnkgZWl0aGVyIHRoZSBjcmVhdG9yIG9yIHRoZSB3b3JrZXIuCgogICAgQGdsLnB1YmxpYy53cml0ZQogICAgZGVmIHJlcXVlc3RfdmVyaWZpY2F0aW9uKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgY2FsbGVyID0gc3RyKGdsLm1lc3NhZ2Uuc2VuZGVyX2FkZHJlc3MpCiAgICAgICAgYXNzZXJ0IGNhbGxlciBpbiAoc2VsZi5jcmVhdG9yLCBzZWxmLndvcmtlciksICJPbmx5IGNyZWF0b3Igb3Igd29ya2VyIGNhbiByZXF1ZXN0IHZlcmlmaWNhdGlvbiIKICAgICAgICBhc3NlcnQgc2VsZi5zdGF0dXMgaW4gKCJzdWJtaXR0ZWQiLCAiZGlzcHV0ZWQiKSwgIlRhc2sgbXVzdCBiZSBzdWJtaXR0ZWQgb3IgZGlzcHV0ZWQgdG8gdmVyaWZ5IgogICAgICAgIHNlbGYuX3ZlcmlmeV9zdWJtaXNzaW9uKCkKCiAgICBAZ2wucHVibGljLndyaXRlCiAgICBkZWYgZGlzcHV0ZShzZWxmLCByZWFzb246IHN0cikgLT4gTm9uZToKICAgICAgICBjYWxsZXIgPSBzdHIoZ2wubWVzc2FnZS5zZW5kZXJfYWRkcmVzcykKICAgICAgICBhc3NlcnQgY2FsbGVyIGluIChzZWxmLmNyZWF0b3IsIHNlbGYud29ya2VyKSwgIk9ubHkgY3JlYXRvciBvciB3b3JrZXIgY2FuIGRpc3B1dGUiCiAgICAgICAgYXNzZXJ0IHNlbGYuc3RhdHVzIGluICgidmVyaWZpZWQiLCAicmVqZWN0ZWQiKSwgIkNhbiBvbmx5IGRpc3B1dGUgYSBkZWNpZGVkIHZlcmlmaWNhdGlvbiIKICAgICAgICBzZWxmLmRpc3B1dGVfY291bnQgKz0gMQogICAgICAgIHNlbGYuZGlzcHV0ZV9yZWFzb24gPSByZWFzb24KICAgICAgICBzZWxmLnN0YXR1cyA9ICJkaXNwdXRlZCIKICAgICAgICBzZWxmLnZlcmlmaWVkX2F0ID0gMAoKICAgIEBnbC5wdWJsaWMud3JpdGUKICAgIGRlZiBjYW5jZWxfdGFzayhzZWxmKSAtPiBOb25lOgogICAgICAgIGNhbGxlciA9IHN0cihnbC5tZXNzYWdlLnNlbmRlcl9hZGRyZXNzKQogICAgICAgIGFzc2VydCBjYWxsZXIgPT0gc2VsZi5jcmVhdG9yLCAiT25seSBjcmVhdG9yIGNhbiBjYW5jZWwiCiAgICAgICAgYXNzZXJ0IHNlbGYuc3RhdHVzIGluICgib3BlbiIsICJjbGFpbWVkIiksICJDYW5ub3QgY2FuY2VsIGFmdGVyIHN1Ym1pc3Npb24iCiAgICAgICAgc2VsZi5zdGF0dXMgPSAib3BlbiIKICAgICAgICBzZWxmLndvcmtlciA9ICIiCgogICAgQGdsLnB1YmxpYy52aWV3CiAgICBkZWYgZ2V0X3Rhc2tfc3RhdGUoc2VsZikgLT4gZGljdDoKICAgICAgICBjYWxsZXIgPSBzdHIoZ2wubWVzc2FnZS5zZW5kZXJfYWRkcmVzcykKICAgICAgICBpc19wYXJ0eSA9IGNhbGxlciA9PSBzZWxmLmNyZWF0b3Igb3IgY2FsbGVyID09IHNlbGYud29ya2VyCiAgICAgICAgIyBTdWJtaXR0ZWQgZXZpZGVuY2UgaXMgb25seSBtZWFuaW5nZnVsIHRvIGhpZGUgb25jZSBzb21ldGhpbmcgaGFzCiAgICAgICAgIyBhY3R1YWxseSBiZWVuIHN1Ym1pdHRlZCAtIGFuIGVtcHR5IHN0cmluZyBhbHJlYWR5IG1lYW5zICJub3RoaW5nCiAgICAgICAgIyBzdWJtaXR0ZWQgeWV0IiBmb3Igb3Blbi9jbGFpbWVkIHRhc2tzLCBzbyBvbmx5IHJlZGFjdCB3aGVuIHRoZXJlJ3MKICAgICAgICAjIHNvbWV0aGluZyByZWFsIHRvIHJlZGFjdC4KICAgICAgICBoaWRlX2V2aWRlbmNlID0gc2VsZi5zdWJtaXNzaW9uX3VybCAhPSAiIiBhbmQgbm90IGlzX3BhcnR5CiAgICAgICAgZXZpZGVuY2VfdXJsID0gIltwcml2YXRlXSIgaWYgaGlkZV9ldmlkZW5jZSBlbHNlIHNlbGYuc3VibWlzc2lvbl91cmwKICAgICAgICBldmlkZW5jZV9ub3RlID0gIltwcml2YXRlXSIgaWYgaGlkZV9ldmlkZW5jZSBlbHNlIHNlbGYuc3VibWlzc2lvbl9ub3RlCgogICAgICAgIHJldHVybiB7CiAgICAgICAgICAgICJjcmVhdG9yIjogc2VsZi5jcmVhdG9yLAogICAgICAgICAgICAiZmFjdG9yeSI6IHNlbGYuZmFjdG9yeSwKICAgICAgICAgICAgInRpdGxlIjogc2VsZi50aXRsZSwKICAgICAgICAgICAgImNhdGVnb3J5Ijogc2VsZi5jYXRlZ29yeSwKICAgICAgICAgICAgImNhdGVnb3J5X290aGVyIjogc2VsZi5jYXRlZ29yeV9vdGhlciwKICAgICAgICAgICAgInByaW9yaXR5Ijogc2VsZi5wcmlvcml0eSwKICAgICAgICAgICAgImVzdGltYXRlZF9lZmZvcnQiOiBzZWxmLmVzdGltYXRlZF9lZmZvcnQsCiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6IHNlbGYuZGVzY3JpcHRpb24sCiAgICAgICAgICAgICJjcml0ZXJpYSI6IHNlbGYuY3JpdGVyaWEsCiAgICAgICAgICAgICJzdWJtaXNzaW9uX2Zvcm1hdCI6IHNlbGYuc3VibWlzc2lvbl9mb3JtYXQsCiAgICAgICAgICAgICJzdWJtaXNzaW9uX2Zvcm1hdF9vdGhlciI6IHNlbGYuc3VibWlzc2lvbl9mb3JtYXRfb3RoZXIsCiAgICAgICAgICAgICJyZXdhcmRfYW1vdW50Ijogc2VsZi5yZXdhcmRfYW1vdW50LAogICAgICAgICAgICAiZGVhZGxpbmUiOiBzZWxmLmRlYWRsaW5lLAogICAgICAgICAgICAid29ya2VyIjogc2VsZi53b3JrZXIsCiAgICAgICAgICAgICJzdWJtaXNzaW9uX3VybCI6IGV2aWRlbmNlX3VybCwKICAgICAgICAgICAgInN1Ym1pc3Npb25fbm90ZSI6IGV2aWRlbmNlX25vdGUsCiAgICAgICAgICAgICJzdGF0dXMiOiBzZWxmLnN0YXR1cywKICAgICAgICAgICAgInZlcmlmaWNhdGlvbl9yZXN1bHQiOiBzZWxmLnZlcmlmaWNhdGlvbl9yZXN1bHQsCiAgICAgICAgICAgICJkaXNwdXRlX2NvdW50Ijogc2VsZi5kaXNwdXRlX2NvdW50LAogICAgICAgICAgICAiZGlzcHV0ZV9yZWFzb24iOiBzZWxmLmRpc3B1dGVfcmVhc29uLAogICAgICAgICAgICAiY3JlYXRlZF9hdCI6IHNlbGYuY3JlYXRlZF9hdCwKICAgICAgICAgICAgInZlcmlmaWVkX2F0Ijogc2VsZi52ZXJpZmllZF9hdCwKICAgICAgICB9CgogICAgZGVmIF92ZXJpZnlfc3VibWlzc2lvbihzZWxmKToKICAgICAgICB0aXRsZSA9IHNlbGYudGl0bGUKICAgICAgICBkZXNjcmlwdGlvbiA9IHNlbGYuZGVzY3JpcHRpb24KICAgICAgICBjcml0ZXJpYSA9IHNlbGYuY3JpdGVyaWEKICAgICAgICBzdWJtaXNzaW9uX3VybCA9IHNlbGYuc3VibWlzc2lvbl91cmwKICAgICAgICBzdWJtaXNzaW9uX25vdGUgPSBzZWxmLnN1Ym1pc3Npb25fbm90ZQogICAgICAgIHN1Ym1pc3Npb25fZm9ybWF0ID0gc2VsZi5zdWJtaXNzaW9uX2Zvcm1hdF9vdGhlciBvciBzZWxmLnN1Ym1pc3Npb25fZm9ybWF0CiAgICAgICAgZGlzcHV0ZV9yZWFzb24gPSBzZWxmLmRpc3B1dGVfcmVhc29uCiAgICAgICAgaXNfcmVkaXNwdXRlID0gc2VsZi5kaXNwdXRlX2NvdW50ID4gMAoKICAgICAgICBkZWYgYW5hbHl6ZSgpOgogICAgICAgICAgICAjIEZldGNoIHRoZSBldmlkZW5jZSBmcmVzaCwgZXZlcnkgdGltZSB0aGlzIGlzIGNhbGxlZAogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICB3ZWJfZGF0YSA9IGdsLm5vbmRldC53ZWIucmVuZGVyKHN1Ym1pc3Npb25fdXJsLCBtb2RlPSJ0ZXh0IikKICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICAgICAgcmFpc2UgZ2wudm0uVXNlckVycm9yKGYie0VSUk9SX1RSQU5TSUVOVH0gZmFpbGVkIHRvIGZldGNoIHtzdWJtaXNzaW9uX3VybH06IHtlfSIpCgogICAgICAgICAgICBkaXNwdXRlX2NvbnRleHQgPSAiIgogICAgICAgICAgICBpZiBpc19yZWRpc3B1dGUgYW5kIGRpc3B1dGVfcmVhc29uOgogICAgICAgICAgICAgICAgZGlzcHV0ZV9jb250ZXh0ID0gZiIiIgpUaGlzIHN1Ym1pc3Npb24gd2FzIERJU1BVVEVEIGJ5IG9uZSBvZiB0aGUgcGFydGllcy4gUmUtZXhhbWluZSB0aGUgZXZpZGVuY2UKY2FyZWZ1bGx5IGluIGxpZ2h0IG9mIHRoZSBkaXNwdXRlIHJlYXNvbiBiZWxvdywgYW5kIGRvIG5vdCBzaW1wbHkgcmVwZWF0IGEKcHJpb3IgdmVyZGljdCAtIGZvcm0geW91ciBvd24gaW5kZXBlbmRlbnQganVkZ21lbnQgZnJvbSB0aGUgY3VycmVudCBldmlkZW5jZS4KCkRJU1BVVEUgUkVBU09OOiB7ZGlzcHV0ZV9yZWFzb259CiIiIgoKICAgICAgICAgICAgbm90ZV9jb250ZXh0ID0gZiJcbldPUktFUidTIE5PVEU6IHtzdWJtaXNzaW9uX25vdGV9XG4iIGlmIHN1Ym1pc3Npb25fbm90ZSBlbHNlICIiCgogICAgICAgICAgICBwcm9tcHQgPSBmIiIiWW91IGFyZSBhbiBBSSByZXZpZXdlciB2ZXJpZnlpbmcgdGFzayBjb21wbGV0aW9uLgoKVEFTSyBUSVRMRToge3RpdGxlfQpUQVNLIERFU0NSSVBUSU9OOiB7ZGVzY3JpcHRpb259CkNPTVBMRVRJT04gQ1JJVEVSSUE6IHtjcml0ZXJpYX0KRVhQRUNURUQgRVZJREVOQ0UgRk9STUFUOiB7c3VibWlzc2lvbl9mb3JtYXR9CgpTVUJNSVRURUQgRVZJREVOQ0UgVVJMOiB7c3VibWlzc2lvbl91cmx9Cntub3RlX2NvbnRleHR9e2Rpc3B1dGVfY29udGV4dH0KRVZJREVOQ0UgQ09OVEVOVDoKe3dlYl9kYXRhWzo4MDAwXX0KCkFuYWx5emUgdGhlIGV2aWRlbmNlIGFnYWluc3QgdGhlIGNvbXBsZXRpb24gY3JpdGVyaWEsIGtlZXBpbmcgaW4gbWluZCB0aGUgZXhwZWN0ZWQKZXZpZGVuY2UgZm9ybWF0IGFib3ZlIChlLmcuIGEgR2l0SHViIHJlcG8sIGEgbGl2ZSBkZXBsb3llZCBhcHAsIGEgdmlkZW8sIGEgZG9jdW1lbnQpLgpEZXRlcm1pbmUgaWYgdGhlIHRhc2sgaGFzIGJlZW4gZ2VudWluZWx5IGNvbXBsZXRlZC4KClJlc3BvbmQgaW4gdmFsaWQgSlNPTiBmb3JtYXQ6Cnt7InZlcmlmaWVkIjogdHJ1ZS9mYWxzZSwgImNvbmZpZGVuY2UiOiAwLTEwMCwgInJlYXNvbmluZyI6ICJkZXRhaWxlZCBleHBsYW5hdGlvbiBvZiB5b3VyIHZlcmlmaWNhdGlvbiJ9fQoKQmUgc3RyaWN0IGJ1dCBmYWlyLiBMb29rIGZvciBldmlkZW5jZSB0aGF0IHRoZSBjcml0ZXJpYSBhcmUgbWV0LiIiIgoKICAgICAgICAgICAgcmVzdWx0ID0gZ2wubm9uZGV0LmV4ZWNfcHJvbXB0KHByb21wdCwgcmVzcG9uc2VfZm9ybWF0PSJqc29uIikKCiAgICAgICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHJlc3VsdCwgZGljdCkgb3IgInZlcmlmaWVkIiBub3QgaW4gcmVzdWx0OgogICAgICAgICAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgICAgICAgICAidmVyaWZpZWQiOiBGYWxzZSwKICAgICAgICAgICAgICAgICAgICAiY29uZmlkZW5jZSI6IDAsCiAgICAgICAgICAgICAgICAgICAgInJlYXNvbmluZyI6ICJBSSB2ZXJpZmljYXRpb24gcHJvZHVjZWQgbWFsZm9ybWVkIG91dHB1dC4gTWFudWFsIHJldmlldyBuZWVkZWQuIiwKICAgICAgICAgICAgICAgIH0KCiAgICAgICAgICAgIHJldHVybiB7CiAgICAgICAgICAgICAgICAidmVyaWZpZWQiOiBib29sKHJlc3VsdC5nZXQoInZlcmlmaWVkIiwgRmFsc2UpKSwKICAgICAgICAgICAgICAgICJjb25maWRlbmNlIjogaW50KHJlc3VsdC5nZXQoImNvbmZpZGVuY2UiLCAwKSBvciAwKSwKICAgICAgICAgICAgICAgICJyZWFzb25pbmciOiBzdHIocmVzdWx0LmdldCgicmVhc29uaW5nIiwgIiIpKSwKICAgICAgICAgICAgfQoKICAgICAgICBwYXJzZWQgPSBnbC5lcV9wcmluY2lwbGUucHJvbXB0X2NvbXBhcmF0aXZlKAogICAgICAgICAgICBhbmFseXplLAogICAgICAgICAgICBwcmluY2lwbGU9KAogICAgICAgICAgICAgICAgImB2ZXJpZmllZGAgbXVzdCBiZSBleGFjdGx5IHRoZSBzYW1lLiBgY29uZmlkZW5jZWAgc2hvdWxkIGJlIHdpdGhpbiAiCiAgICAgICAgICAgICAgICAiMTUgcG9pbnRzIG9mIGVhY2ggb3RoZXIuIGByZWFzb25pbmdgIG1heSBkaWZmZXIgaW4gd29yZGluZyBidXQgc2hvdWxkICIKICAgICAgICAgICAgICAgICJyZWZlcmVuY2Ugc2ltaWxhciBldmlkZW5jZS4iCiAgICAgICAgICAgICksCiAgICAgICAgKQoKICAgICAgICBub3cgPSBpbnQoZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykudGltZXN0YW1wKCkpCiAgICAgICAgc2VsZi52ZXJpZmljYXRpb25fcmVzdWx0ID0ganNvbi5kdW1wcyhwYXJzZWQpCiAgICAgICAgc2VsZi5zdGF0dXMgPSAidmVyaWZpZWQiIGlmIHBhcnNlZC5nZXQoInZlcmlmaWVkIikgZWxzZSAicmVqZWN0ZWQiCiAgICAgICAgc2VsZi52ZXJpZmllZF9hdCA9IG5vdwo="


@gl.evm.contract_interface
class _Recipient:
    class View:
        pass

    class Write:
        pass


class TaskFactory(gl.Contract):
    tasks: DynArray[Address]
    escrow: TreeMap[Address, u256]
    escrow_released: TreeMap[Address, bool]
    task_count: u256

    def __init__(self):
        self.task_count = 0

    @gl.public.write.payable
    def create_task(
        self,
        title: str,
        category: str,
        category_other: str,
        priority: str,
        estimated_effort: str,
        description: str,
        criteria: str,
        submission_format: str,
        submission_format_other: str,
        reward_amount: int,
        deadline: int,
    ) -> str:
        expected_value = u256(reward_amount) * u256(10**18)
        assert gl.message.value == expected_value, "Sent value must equal reward_amount GEN (in atto-GEN)"

        creator = str(gl.message.sender_address)
        factory_address = str(gl.message.contract_address)
        verifier_code = base64.b64decode(TASK_VERIFIER_CODE_B64)

        addr = gl.deploy_contract(
            code=verifier_code,
            args=[
                creator,
                factory_address,
                title,
                category,
                category_other,
                priority,
                estimated_effort,
                description,
                criteria,
                submission_format,
                submission_format_other,
                reward_amount,
                deadline,
            ],
            salt_nonce=int(self.task_count) + 1,
            on="accepted",
        )

        self.tasks.append(addr)
        self.escrow[addr] = gl.message.value
        self.escrow_released[addr] = False
        self.task_count += 1
        return str(addr)

    @gl.public.write
    def release_funds(self, task_address: str) -> None:
        addr = Address(task_address)
        assert addr in self.escrow, "Unknown task"
        assert not self.escrow_released.get(addr, False), "Escrow already released"

        other = gl.get_contract_at(addr)
        state = other.view().get_task_state()

        status = state["status"]
        assert status in ("verified", "rejected"), "Task has not been decided yet"

        verified_at = int(state["verified_at"])
        assert verified_at > 0, "No verification timestamp recorded"

        now = int(datetime.now(timezone.utc).timestamp())
        assert now >= verified_at + RELEASE_WINDOW_SECONDS, "24h dispute window still open"

        amount = self.escrow[addr]
        recipient = state["worker"] if status == "verified" else state["creator"]

        self.escrow_released[addr] = True
        _Recipient(Address(recipient)).emit_transfer(value=amount)

    @gl.public.view
    def get_all_tasks(self) -> list[str]:
        return [str(a) for a in self.tasks]

    @gl.public.view
    def get_task_count(self) -> int:
        return int(self.task_count)

    @gl.public.view
    def get_escrow_status(self, task_address: str) -> dict:
        addr = Address(task_address)
        return {
            "locked_amount": self.escrow.get(addr, u256(0)),
            "released": self.escrow_released.get(addr, False),
        }
