# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }

# ProofWork TaskFactory - deploys TaskVerifier child contracts and holds their
# GEN reward escrow. This is the contract deployed/hardcoded per network;
# TaskVerifier is never deployed directly.
#
# TASK_VERIFIER_CODE_B64 below is generated from task_verifier.py - do not
# hand-edit it. Run `python3 contracts/generate_factory.py` after changing
# task_verifier.py to regenerate it.

from genlayer import *

from datetime import datetime, timezone
import base64

RELEASE_WINDOW_SECONDS = 86400  # 24h dispute window before escrow auto-releases

TASK_VERIFIER_CODE_B64 = "IyB7ICJEZXBlbmRzIjogInB5LWdlbmxheWVyOjFqYjQ1YWE4eW5oMmE5Yzl4bjNiN3FxaDhzbTVxOTNod2ZwN2pxbXdzZmhoOGpwejA5aDYiIH0KCiMgQUktVmVyaWZpZWQgVGFzayBDb21wbGV0aW9uIC0gR2VuTGF5ZXIgSW50ZWxsaWdlbnQgQ29udHJhY3QKIyBEZXBsb3llZCBhcyBhIGNoaWxkIG9mIFRhc2tGYWN0b3J5IChzZWUgdGFza19mYWN0b3J5LnB5KSAtIG5vdCBkZXBsb3llZCBkaXJlY3RseS4KCmZyb20gZ2VubGF5ZXIgaW1wb3J0ICoKCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lLCB0aW1lem9uZQppbXBvcnQganNvbgoKRVJST1JfRVhQRUNURUQgPSAiW0VYUEVDVEVEXSIgICMgYnVzaW5lc3MgbG9naWMgLSBkZXRlcm1pbmlzdGljLCBleGFjdCBtYXRjaApFUlJPUl9FWFRFUk5BTCA9ICJbRVhURVJOQUxdIiAgIyBleHRlcm5hbCBBUEkgNHh4IC0gZGV0ZXJtaW5pc3RpYywgZXhhY3QgbWF0Y2gKRVJST1JfVFJBTlNJRU5UID0gIltUUkFOU0lFTlRdIiAgIyBuZXR3b3JrLzV4eCAtIG5vbi1kZXRlcm1pbmlzdGljLCBhZ3JlZSBpZiBib3RoIHRyYW5zaWVudApFUlJPUl9MTE0gPSAiW0xMTV9FUlJPUl0iICAjIExMTSBtaXNiZWhhdmlvciAtIGFsd2F5cyBkaXNhZ3JlZSwgZm9yY2Ugcm90YXRpb24KCk1BWF9ESVNQVVRFUyA9IDMgICMgYWZ0ZXIgdGhpcyBtYW55IGRpc3B1dGVzLCB0aGUgbGFzdCB2ZXJkaWN0IGlzIGZpbmFsCgoKY2xhc3MgVGFza1ZlcmlmaWVyKGdsLkNvbnRyYWN0KToKICAgIGNyZWF0b3I6IHN0cgogICAgZmFjdG9yeTogc3RyCiAgICB0aXRsZTogc3RyCiAgICBjYXRlZ29yeTogc3RyCiAgICBjYXRlZ29yeV9vdGhlcjogc3RyCiAgICBwcmlvcml0eTogc3RyCiAgICBlc3RpbWF0ZWRfZWZmb3J0OiBzdHIKICAgIGRlc2NyaXB0aW9uOiBzdHIKICAgIGNyaXRlcmlhOiBzdHIKICAgIHN1Ym1pc3Npb25fZm9ybWF0OiBzdHIKICAgIHN1Ym1pc3Npb25fZm9ybWF0X290aGVyOiBzdHIKICAgIHJld2FyZF9hbW91bnQ6IHUyNTYKICAgIGRlYWRsaW5lOiB1MjU2ICAjIHVuaXggdGltZXN0YW1wOyB3b3JrZXIgbXVzdCBzdWJtaXQgYmVmb3JlIHRoaXMKICAgIHdvcmtlcjogc3RyCiAgICBzdWJtaXNzaW9uX3VybDogc3RyCiAgICBzdWJtaXNzaW9uX25vdGU6IHN0cgogICAgc3VibWlzc2lvbl9zbmFwc2hvdDogc3RyICAjIGV2aWRlbmNlIGNvbnRlbnQsIGZyb3plbiBhdCBzdWJtaXNzaW9uIHRpbWUgLSBuZXZlciByZS1mZXRjaGVkCiAgICBzdGF0dXM6IHN0ciAgIyAib3BlbiIsICJjbGFpbWVkIiwgInN1Ym1pdHRlZCIsICJ2ZXJpZmllZCIsICJyZWplY3RlZCIsICJkaXNwdXRlZCIsICJjYW5jZWxsZWQiLCAiZXhwaXJlZCIKICAgIHZlcmlmaWNhdGlvbl9yZXN1bHQ6IHN0cgogICAgZGlzcHV0ZV9jb3VudDogdTI1NgogICAgZGlzcHV0ZV9yZWFzb246IHN0cgogICAgY3JlYXRlZF9hdDogdTI1NgogICAgdmVyaWZpZWRfYXQ6IHUyNTYgICMgc2V0IHdoZW4gc3RhdHVzIGZpcnN0IGJlY29tZXMgdmVyaWZpZWQvcmVqZWN0ZWQ7IGVzY3JvdyByZWxlYXNlIHdpbmRvdyBzdGFydHMgaGVyZQoKICAgIGRlZiBfX2luaXRfXygKICAgICAgICBzZWxmLAogICAgICAgIGNyZWF0b3I6IHN0ciwKICAgICAgICBmYWN0b3J5OiBzdHIsCiAgICAgICAgdGl0bGU6IHN0ciwKICAgICAgICBjYXRlZ29yeTogc3RyLAogICAgICAgIGNhdGVnb3J5X290aGVyOiBzdHIsCiAgICAgICAgcHJpb3JpdHk6IHN0ciwKICAgICAgICBlc3RpbWF0ZWRfZWZmb3J0OiBzdHIsCiAgICAgICAgZGVzY3JpcHRpb246IHN0ciwKICAgICAgICBjcml0ZXJpYTogc3RyLAogICAgICAgIHN1Ym1pc3Npb25fZm9ybWF0OiBzdHIsCiAgICAgICAgc3VibWlzc2lvbl9mb3JtYXRfb3RoZXI6IHN0ciwKICAgICAgICByZXdhcmRfYW1vdW50OiBpbnQsCiAgICAgICAgZGVhZGxpbmU6IGludCwKICAgICk6CiAgICAgICAgbm93ID0gaW50KGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLnRpbWVzdGFtcCgpKQogICAgICAgIGFzc2VydCBkZWFkbGluZSA+IG5vdywgIkRlYWRsaW5lIG11c3QgYmUgaW4gdGhlIGZ1dHVyZSIKICAgICAgICBzZWxmLmNyZWF0b3IgPSBjcmVhdG9yCiAgICAgICAgc2VsZi5mYWN0b3J5ID0gZmFjdG9yeQogICAgICAgIHNlbGYudGl0bGUgPSB0aXRsZQogICAgICAgIHNlbGYuY2F0ZWdvcnkgPSBjYXRlZ29yeQogICAgICAgIHNlbGYuY2F0ZWdvcnlfb3RoZXIgPSBjYXRlZ29yeV9vdGhlcgogICAgICAgIHNlbGYucHJpb3JpdHkgPSBwcmlvcml0eQogICAgICAgIHNlbGYuZXN0aW1hdGVkX2VmZm9ydCA9IGVzdGltYXRlZF9lZmZvcnQKICAgICAgICBzZWxmLmRlc2NyaXB0aW9uID0gZGVzY3JpcHRpb24KICAgICAgICBzZWxmLmNyaXRlcmlhID0gY3JpdGVyaWEKICAgICAgICBzZWxmLnN1Ym1pc3Npb25fZm9ybWF0ID0gc3VibWlzc2lvbl9mb3JtYXQKICAgICAgICBzZWxmLnN1Ym1pc3Npb25fZm9ybWF0X290aGVyID0gc3VibWlzc2lvbl9mb3JtYXRfb3RoZXIKICAgICAgICBzZWxmLnJld2FyZF9hbW91bnQgPSByZXdhcmRfYW1vdW50CiAgICAgICAgc2VsZi5kZWFkbGluZSA9IGRlYWRsaW5lCiAgICAgICAgc2VsZi53b3JrZXIgPSAiIgogICAgICAgIHNlbGYuc3VibWlzc2lvbl91cmwgPSAiIgogICAgICAgIHNlbGYuc3VibWlzc2lvbl9ub3RlID0gIiIKICAgICAgICBzZWxmLnN1Ym1pc3Npb25fc25hcHNob3QgPSAiIgogICAgICAgIHNlbGYuc3RhdHVzID0gIm9wZW4iCiAgICAgICAgc2VsZi52ZXJpZmljYXRpb25fcmVzdWx0ID0gIiIKICAgICAgICBzZWxmLmRpc3B1dGVfY291bnQgPSAwCiAgICAgICAgc2VsZi5kaXNwdXRlX3JlYXNvbiA9ICIiCiAgICAgICAgc2VsZi5jcmVhdGVkX2F0ID0gbm93CiAgICAgICAgc2VsZi52ZXJpZmllZF9hdCA9IDAKCiAgICBAZ2wucHVibGljLndyaXRlCiAgICBkZWYgY2xhaW1fdGFzayhzZWxmKSAtPiBOb25lOgogICAgICAgIGNhbGxlciA9IHN0cihnbC5tZXNzYWdlLnNlbmRlcl9hZGRyZXNzKQogICAgICAgIG5vdyA9IGludChkYXRldGltZS5ub3codGltZXpvbmUudXRjKS50aW1lc3RhbXAoKSkKICAgICAgICBhc3NlcnQgc2VsZi5zdGF0dXMgPT0gIm9wZW4iLCAiVGFzayBpcyBub3Qgb3BlbiIKICAgICAgICBhc3NlcnQgY2FsbGVyICE9IHNlbGYuY3JlYXRvciwgIkNyZWF0b3IgY2Fubm90IGNsYWltIG93biB0YXNrIgogICAgICAgIGFzc2VydCBub3cgPD0gc2VsZi5kZWFkbGluZSwgIlRhc2sgZGVhZGxpbmUgaGFzIHBhc3NlZCIKICAgICAgICBzZWxmLndvcmtlciA9IGNhbGxlcgogICAgICAgIHNlbGYuc3RhdHVzID0gImNsYWltZWQiCgogICAgQGdsLnB1YmxpYy53cml0ZQogICAgZGVmIHN1Ym1pdF93b3JrKHNlbGYsIGV2aWRlbmNlX3VybDogc3RyLCBzdWJtaXNzaW9uX25vdGU6IHN0cikgLT4gTm9uZToKICAgICAgICBjYWxsZXIgPSBzdHIoZ2wubWVzc2FnZS5zZW5kZXJfYWRkcmVzcykKICAgICAgICBub3cgPSBpbnQoZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykudGltZXN0YW1wKCkpCiAgICAgICAgYXNzZXJ0IGNhbGxlciA9PSBzZWxmLndvcmtlciwgIk9ubHkgYXNzaWduZWQgd29ya2VyIGNhbiBzdWJtaXQiCiAgICAgICAgYXNzZXJ0IHNlbGYuc3RhdHVzID09ICJjbGFpbWVkIiwgIlRhc2sgbXVzdCBiZSBjbGFpbWVkIGZpcnN0IgogICAgICAgIGFzc2VydCBub3cgPD0gc2VsZi5kZWFkbGluZSwgIlRhc2sgZGVhZGxpbmUgaGFzIHBhc3NlZCIKCiAgICAgICAgdXJsX2xvd2VyID0gZXZpZGVuY2VfdXJsLmxvd2VyKCkuc3RyaXAoKQogICAgICAgIGFzc2VydCB1cmxfbG93ZXIuc3RhcnRzd2l0aCgiaHR0cDovLyIpIG9yIHVybF9sb3dlci5zdGFydHN3aXRoKCJodHRwczovLyIpLCBcCiAgICAgICAgICAgICJFdmlkZW5jZSBtdXN0IGJlIGEgdmFsaWQgVVJMIgogICAgICAgIGV4cGVjdGVkX2Zvcm1hdCA9IHNlbGYuc3VibWlzc2lvbl9mb3JtYXQKICAgICAgICBpZiBleHBlY3RlZF9mb3JtYXQgPT0gIkdpdEh1YiBSZXBvc2l0b3J5IjoKICAgICAgICAgICAgYXNzZXJ0ICJnaXRodWIuY29tIiBpbiB1cmxfbG93ZXIsIFwKICAgICAgICAgICAgICAgICJUaGlzIHRhc2sgZXhwZWN0cyBhIEdpdEh1YiBSZXBvc2l0b3J5IFVSTCAoZ2l0aHViLmNvbSkiCgogICAgICAgICMgQ29tbWl0IHRoZSBldmlkZW5jZSBjb250ZW50IG5vdywgb25jZSAtIGV2ZXJ5IHZlcmlmaWNhdGlvbiAoaW5jbHVkaW5nCiAgICAgICAgIyByZS12ZXJpZmljYXRpb25zIGFmdGVyIGEgZGlzcHV0ZSkganVkZ2VzIHRoaXMgZnJvemVuIHNuYXBzaG90LCBuZXZlciBhCiAgICAgICAgIyBsaXZlIHJlLWZldGNoLCBzbyB0aGUgY29udGVudCBiZWluZyBqdWRnZWQgY2FuJ3QgZHJpZnQgYWZ0ZXIgc3VibWlzc2lvbi4KICAgICAgICBkZWYgZmV0Y2hfZXZpZGVuY2UoKToKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgcmV0dXJuIGdsLm5vbmRldC53ZWIucmVuZGVyKGV2aWRlbmNlX3VybCwgbW9kZT0idGV4dCIpWzo4MDAwXQogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgICAgICByYWlzZSBnbC52bS5Vc2VyRXJyb3IoZiJ7RVJST1JfVFJBTlNJRU5UfSBmYWlsZWQgdG8gZmV0Y2gge2V2aWRlbmNlX3VybH06IHtlfSIpCgogICAgICAgIGNvbW1pdHRlZF9jb250ZW50ID0gZ2wuZXFfcHJpbmNpcGxlLnByb21wdF9jb21wYXJhdGl2ZSgKICAgICAgICAgICAgZmV0Y2hfZXZpZGVuY2UsCiAgICAgICAgICAgIHByaW5jaXBsZT0oCiAgICAgICAgICAgICAgICAiQm90aCBmZXRjaGVzIG11c3QgYmUgb2YgdGhlIHNhbWUgdW5kZXJseWluZyBwYWdlIG9yIHJlc291cmNlLiBNaW5vciAiCiAgICAgICAgICAgICAgICAiZm9ybWF0dGluZyBvciBpbmNpZGVudGFsIGR5bmFtaWMgZWxlbWVudHMgKHRpbWVzdGFtcHMsIGNvdW50ZXJzKSBtYXkgIgogICAgICAgICAgICAgICAgImRpZmZlciwgYnV0IHRoZSBzdWJzdGFudGl2ZSBjb250ZW50IG11c3QgbWF0Y2guIgogICAgICAgICAgICApLAogICAgICAgICkKCiAgICAgICAgc2VsZi5zdWJtaXNzaW9uX3VybCA9IGV2aWRlbmNlX3VybAogICAgICAgIHNlbGYuc3VibWlzc2lvbl9ub3RlID0gc3VibWlzc2lvbl9ub3RlCiAgICAgICAgc2VsZi5zdWJtaXNzaW9uX3NuYXBzaG90ID0gY29tbWl0dGVkX2NvbnRlbnQKICAgICAgICBzZWxmLnN0YXR1cyA9ICJzdWJtaXR0ZWQiCiAgICAgICAgIyBFdmlkZW5jZSBpcyBub3cgbG9ja2VkIGluLiBBSSB2ZXJpZmljYXRpb24gbXVzdCBiZSB0cmlnZ2VyZWQgc2VwYXJhdGVseQogICAgICAgICMgdmlhIHJlcXVlc3RfdmVyaWZpY2F0aW9uKCkgYnkgZWl0aGVyIHRoZSBjcmVhdG9yIG9yIHRoZSB3b3JrZXIuCgogICAgQGdsLnB1YmxpYy53cml0ZQogICAgZGVmIHJlcXVlc3RfdmVyaWZpY2F0aW9uKHNlbGYpIC0+IE5vbmU6CiAgICAgICAgY2FsbGVyID0gc3RyKGdsLm1lc3NhZ2Uuc2VuZGVyX2FkZHJlc3MpCiAgICAgICAgYXNzZXJ0IGNhbGxlciBpbiAoc2VsZi5jcmVhdG9yLCBzZWxmLndvcmtlciksICJPbmx5IGNyZWF0b3Igb3Igd29ya2VyIGNhbiByZXF1ZXN0IHZlcmlmaWNhdGlvbiIKICAgICAgICBhc3NlcnQgc2VsZi5zdGF0dXMgaW4gKCJzdWJtaXR0ZWQiLCAiZGlzcHV0ZWQiKSwgIlRhc2sgbXVzdCBiZSBzdWJtaXR0ZWQgb3IgZGlzcHV0ZWQgdG8gdmVyaWZ5IgogICAgICAgIHNlbGYuX3ZlcmlmeV9zdWJtaXNzaW9uKCkKCiAgICBAZ2wucHVibGljLndyaXRlCiAgICBkZWYgZGlzcHV0ZShzZWxmLCByZWFzb246IHN0cikgLT4gTm9uZToKICAgICAgICBjYWxsZXIgPSBzdHIoZ2wubWVzc2FnZS5zZW5kZXJfYWRkcmVzcykKICAgICAgICBhc3NlcnQgY2FsbGVyIGluIChzZWxmLmNyZWF0b3IsIHNlbGYud29ya2VyKSwgIk9ubHkgY3JlYXRvciBvciB3b3JrZXIgY2FuIGRpc3B1dGUiCiAgICAgICAgYXNzZXJ0IHNlbGYuc3RhdHVzIGluICgidmVyaWZpZWQiLCAicmVqZWN0ZWQiKSwgIkNhbiBvbmx5IGRpc3B1dGUgYSBkZWNpZGVkIHZlcmlmaWNhdGlvbiIKICAgICAgICBhc3NlcnQgc2VsZi5kaXNwdXRlX2NvdW50IDwgTUFYX0RJU1BVVEVTLCAiTWF4aW11bSBkaXNwdXRlcyByZWFjaGVkIC0gZGVjaXNpb24gaXMgZmluYWwiCiAgICAgICAgc2VsZi5kaXNwdXRlX2NvdW50ICs9IDEKICAgICAgICBzZWxmLmRpc3B1dGVfcmVhc29uID0gcmVhc29uCiAgICAgICAgc2VsZi5zdGF0dXMgPSAiZGlzcHV0ZWQiCiAgICAgICAgc2VsZi52ZXJpZmllZF9hdCA9IDAKCiAgICBAZ2wucHVibGljLndyaXRlCiAgICBkZWYgY2FuY2VsX3Rhc2soc2VsZikgLT4gTm9uZToKICAgICAgICBjYWxsZXIgPSBzdHIoZ2wubWVzc2FnZS5zZW5kZXJfYWRkcmVzcykKICAgICAgICBhc3NlcnQgY2FsbGVyID09IHNlbGYuY3JlYXRvciwgIk9ubHkgY3JlYXRvciBjYW4gY2FuY2VsIgogICAgICAgIGFzc2VydCBzZWxmLnN0YXR1cyA9PSAib3BlbiIsICJDYW4gb25seSBjYW5jZWwgYmVmb3JlIHRoZSB0YXNrIGlzIGNsYWltZWQiCiAgICAgICAgc2VsZi5zdGF0dXMgPSAiY2FuY2VsbGVkIgoKICAgIEBnbC5wdWJsaWMud3JpdGUKICAgIGRlZiBleHBpcmVfdGFzayhzZWxmKSAtPiBOb25lOgogICAgICAgIG5vdyA9IGludChkYXRldGltZS5ub3codGltZXpvbmUudXRjKS50aW1lc3RhbXAoKSkKICAgICAgICBhc3NlcnQgbm93ID4gc2VsZi5kZWFkbGluZSwgIkRlYWRsaW5lIGhhcyBub3QgcGFzc2VkIHlldCIKICAgICAgICBhc3NlcnQgc2VsZi5zdGF0dXMgaW4gKCJvcGVuIiwgImNsYWltZWQiKSwgXAogICAgICAgICAgICAiVGFzayBhbHJlYWR5IGhhcyBhIHN1Ym1pc3Npb24gb3IgaXMgYWxyZWFkeSBkZWNpZGVkIgogICAgICAgIHNlbGYuc3RhdHVzID0gImV4cGlyZWQiCgogICAgQGdsLnB1YmxpYy52aWV3CiAgICBkZWYgZ2V0X3Rhc2tfc3RhdGUoc2VsZikgLT4gZGljdDoKICAgICAgICBjYWxsZXIgPSBzdHIoZ2wubWVzc2FnZS5zZW5kZXJfYWRkcmVzcykKICAgICAgICBpc19wYXJ0eSA9IGNhbGxlciA9PSBzZWxmLmNyZWF0b3Igb3IgY2FsbGVyID09IHNlbGYud29ya2VyCiAgICAgICAgIyBTdWJtaXR0ZWQgZXZpZGVuY2UgaXMgb25seSBtZWFuaW5nZnVsIHRvIGhpZGUgb25jZSBzb21ldGhpbmcgaGFzCiAgICAgICAgIyBhY3R1YWxseSBiZWVuIHN1Ym1pdHRlZCAtIGFuIGVtcHR5IHN0cmluZyBhbHJlYWR5IG1lYW5zICJub3RoaW5nCiAgICAgICAgIyBzdWJtaXR0ZWQgeWV0IiBmb3Igb3Blbi9jbGFpbWVkIHRhc2tzLCBzbyBvbmx5IHJlZGFjdCB3aGVuIHRoZXJlJ3MKICAgICAgICAjIHNvbWV0aGluZyByZWFsIHRvIHJlZGFjdC4KICAgICAgICBoaWRlX2V2aWRlbmNlID0gc2VsZi5zdWJtaXNzaW9uX3VybCAhPSAiIiBhbmQgbm90IGlzX3BhcnR5CiAgICAgICAgZXZpZGVuY2VfdXJsID0gIltwcml2YXRlXSIgaWYgaGlkZV9ldmlkZW5jZSBlbHNlIHNlbGYuc3VibWlzc2lvbl91cmwKICAgICAgICBldmlkZW5jZV9ub3RlID0gIltwcml2YXRlXSIgaWYgaGlkZV9ldmlkZW5jZSBlbHNlIHNlbGYuc3VibWlzc2lvbl9ub3RlCgogICAgICAgIHJldHVybiB7CiAgICAgICAgICAgICJjcmVhdG9yIjogc2VsZi5jcmVhdG9yLAogICAgICAgICAgICAiZmFjdG9yeSI6IHNlbGYuZmFjdG9yeSwKICAgICAgICAgICAgInRpdGxlIjogc2VsZi50aXRsZSwKICAgICAgICAgICAgImNhdGVnb3J5Ijogc2VsZi5jYXRlZ29yeSwKICAgICAgICAgICAgImNhdGVnb3J5X290aGVyIjogc2VsZi5jYXRlZ29yeV9vdGhlciwKICAgICAgICAgICAgInByaW9yaXR5Ijogc2VsZi5wcmlvcml0eSwKICAgICAgICAgICAgImVzdGltYXRlZF9lZmZvcnQiOiBzZWxmLmVzdGltYXRlZF9lZmZvcnQsCiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6IHNlbGYuZGVzY3JpcHRpb24sCiAgICAgICAgICAgICJjcml0ZXJpYSI6IHNlbGYuY3JpdGVyaWEsCiAgICAgICAgICAgICJzdWJtaXNzaW9uX2Zvcm1hdCI6IHNlbGYuc3VibWlzc2lvbl9mb3JtYXQsCiAgICAgICAgICAgICJzdWJtaXNzaW9uX2Zvcm1hdF9vdGhlciI6IHNlbGYuc3VibWlzc2lvbl9mb3JtYXRfb3RoZXIsCiAgICAgICAgICAgICJyZXdhcmRfYW1vdW50Ijogc2VsZi5yZXdhcmRfYW1vdW50LAogICAgICAgICAgICAiZGVhZGxpbmUiOiBzZWxmLmRlYWRsaW5lLAogICAgICAgICAgICAid29ya2VyIjogc2VsZi53b3JrZXIsCiAgICAgICAgICAgICJzdWJtaXNzaW9uX3VybCI6IGV2aWRlbmNlX3VybCwKICAgICAgICAgICAgInN1Ym1pc3Npb25fbm90ZSI6IGV2aWRlbmNlX25vdGUsCiAgICAgICAgICAgICJzdGF0dXMiOiBzZWxmLnN0YXR1cywKICAgICAgICAgICAgInZlcmlmaWNhdGlvbl9yZXN1bHQiOiBzZWxmLnZlcmlmaWNhdGlvbl9yZXN1bHQsCiAgICAgICAgICAgICJkaXNwdXRlX2NvdW50Ijogc2VsZi5kaXNwdXRlX2NvdW50LAogICAgICAgICAgICAiZGlzcHV0ZV9yZWFzb24iOiBzZWxmLmRpc3B1dGVfcmVhc29uLAogICAgICAgICAgICAiY3JlYXRlZF9hdCI6IHNlbGYuY3JlYXRlZF9hdCwKICAgICAgICAgICAgInZlcmlmaWVkX2F0Ijogc2VsZi52ZXJpZmllZF9hdCwKICAgICAgICB9CgogICAgZGVmIF92ZXJpZnlfc3VibWlzc2lvbihzZWxmKToKICAgICAgICB0aXRsZSA9IHNlbGYudGl0bGUKICAgICAgICBkZXNjcmlwdGlvbiA9IHNlbGYuZGVzY3JpcHRpb24KICAgICAgICBjcml0ZXJpYSA9IHNlbGYuY3JpdGVyaWEKICAgICAgICBzdWJtaXNzaW9uX3VybCA9IHNlbGYuc3VibWlzc2lvbl91cmwKICAgICAgICBzdWJtaXNzaW9uX25vdGUgPSBzZWxmLnN1Ym1pc3Npb25fbm90ZQogICAgICAgIHN1Ym1pc3Npb25fZm9ybWF0ID0gc2VsZi5zdWJtaXNzaW9uX2Zvcm1hdF9vdGhlciBvciBzZWxmLnN1Ym1pc3Npb25fZm9ybWF0CiAgICAgICAgZGlzcHV0ZV9yZWFzb24gPSBzZWxmLmRpc3B1dGVfcmVhc29uCiAgICAgICAgaXNfcmVkaXNwdXRlID0gc2VsZi5kaXNwdXRlX2NvdW50ID4gMAogICAgICAgICMgSnVkZ2UgdGhlIGNvbnRlbnQgY29tbWl0dGVkIGF0IHN1Ym1pc3Npb24gdGltZSwgbmV2ZXIgYSBsaXZlIHJlLWZldGNoIC0KICAgICAgICAjIHRoaXMgaXMgd2hhdCBrZWVwcyBhIHJlLXZlcmlmaWNhdGlvbiBhZnRlciBhIGRpc3B1dGUgaG9uZXN0OiBpdCBzZWVzCiAgICAgICAgIyBleGFjdGx5IHdoYXQgd2FzIG9yaWdpbmFsbHkgc3VibWl0dGVkLCBub3Qgd2hhdGV2ZXIgdGhlIFVSTCBzZXJ2ZXMgbm93LgogICAgICAgIHdlYl9kYXRhID0gc2VsZi5zdWJtaXNzaW9uX3NuYXBzaG90CgogICAgICAgIGRlZiBhbmFseXplKCk6CiAgICAgICAgICAgIGRpc3B1dGVfY29udGV4dCA9ICIiCiAgICAgICAgICAgIGlmIGlzX3JlZGlzcHV0ZSBhbmQgZGlzcHV0ZV9yZWFzb246CiAgICAgICAgICAgICAgICBkaXNwdXRlX2NvbnRleHQgPSBmIiIiClRoaXMgc3VibWlzc2lvbiB3YXMgRElTUFVURUQgYnkgb25lIG9mIHRoZSBwYXJ0aWVzLiBSZS1leGFtaW5lIHRoZSBldmlkZW5jZQpjYXJlZnVsbHkgaW4gbGlnaHQgb2YgdGhlIGRpc3B1dGUgcmVhc29uIGJlbG93LCBhbmQgZG8gbm90IHNpbXBseSByZXBlYXQgYQpwcmlvciB2ZXJkaWN0IC0gZm9ybSB5b3VyIG93biBpbmRlcGVuZGVudCBqdWRnbWVudCBmcm9tIHRoZSBjdXJyZW50IGV2aWRlbmNlLgoKRElTUFVURSBSRUFTT046IHtkaXNwdXRlX3JlYXNvbn0KIiIiCgogICAgICAgICAgICBub3RlX2NvbnRleHQgPSBmIlxuV09SS0VSJ1MgTk9URToge3N1Ym1pc3Npb25fbm90ZX1cbiIgaWYgc3VibWlzc2lvbl9ub3RlIGVsc2UgIiIKCiAgICAgICAgICAgIHByb21wdCA9IGYiIiJZb3UgYXJlIGFuIEFJIHJldmlld2VyIHZlcmlmeWluZyB0YXNrIGNvbXBsZXRpb24uCgpUQVNLIFRJVExFOiB7dGl0bGV9ClRBU0sgREVTQ1JJUFRJT046IHtkZXNjcmlwdGlvbn0KQ09NUExFVElPTiBDUklURVJJQToge2NyaXRlcmlhfQpFWFBFQ1RFRCBFVklERU5DRSBGT1JNQVQ6IHtzdWJtaXNzaW9uX2Zvcm1hdH0KClNVQk1JVFRFRCBFVklERU5DRSBVUkw6IHtzdWJtaXNzaW9uX3VybH0Ke25vdGVfY29udGV4dH17ZGlzcHV0ZV9jb250ZXh0fQpFVklERU5DRSBDT05URU5UOgp7d2ViX2RhdGFbOjgwMDBdfQoKQW5hbHl6ZSB0aGUgZXZpZGVuY2UgYWdhaW5zdCB0aGUgY29tcGxldGlvbiBjcml0ZXJpYSwga2VlcGluZyBpbiBtaW5kIHRoZSBleHBlY3RlZApldmlkZW5jZSBmb3JtYXQgYWJvdmUgKGUuZy4gYSBHaXRIdWIgcmVwbywgYSBsaXZlIGRlcGxveWVkIGFwcCwgYSB2aWRlbywgYSBkb2N1bWVudCkuCkRldGVybWluZSBpZiB0aGUgdGFzayBoYXMgYmVlbiBnZW51aW5lbHkgY29tcGxldGVkLgoKUmVzcG9uZCBpbiB2YWxpZCBKU09OIGZvcm1hdDoKe3sidmVyaWZpZWQiOiB0cnVlL2ZhbHNlLCAiY29uZmlkZW5jZSI6IDAtMTAwLCAicmVhc29uaW5nIjogImRldGFpbGVkIGV4cGxhbmF0aW9uIG9mIHlvdXIgdmVyaWZpY2F0aW9uIn19CgpCZSBzdHJpY3QgYnV0IGZhaXIuIExvb2sgZm9yIGV2aWRlbmNlIHRoYXQgdGhlIGNyaXRlcmlhIGFyZSBtZXQuIiIiCgogICAgICAgICAgICByZXN1bHQgPSBnbC5ub25kZXQuZXhlY19wcm9tcHQocHJvbXB0LCByZXNwb25zZV9mb3JtYXQ9Impzb24iKQoKICAgICAgICAgICAgaWYgbm90IGlzaW5zdGFuY2UocmVzdWx0LCBkaWN0KSBvciAidmVyaWZpZWQiIG5vdCBpbiByZXN1bHQ6CiAgICAgICAgICAgICAgICByZXR1cm4gewogICAgICAgICAgICAgICAgICAgICJ2ZXJpZmllZCI6IEZhbHNlLAogICAgICAgICAgICAgICAgICAgICJjb25maWRlbmNlIjogMCwKICAgICAgICAgICAgICAgICAgICAicmVhc29uaW5nIjogIkFJIHZlcmlmaWNhdGlvbiBwcm9kdWNlZCBtYWxmb3JtZWQgb3V0cHV0LiBNYW51YWwgcmV2aWV3IG5lZWRlZC4iLAogICAgICAgICAgICAgICAgfQoKICAgICAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgICAgICJ2ZXJpZmllZCI6IGJvb2wocmVzdWx0LmdldCgidmVyaWZpZWQiLCBGYWxzZSkpLAogICAgICAgICAgICAgICAgImNvbmZpZGVuY2UiOiBpbnQocmVzdWx0LmdldCgiY29uZmlkZW5jZSIsIDApIG9yIDApLAogICAgICAgICAgICAgICAgInJlYXNvbmluZyI6IHN0cihyZXN1bHQuZ2V0KCJyZWFzb25pbmciLCAiIikpLAogICAgICAgICAgICB9CgogICAgICAgIHBhcnNlZCA9IGdsLmVxX3ByaW5jaXBsZS5wcm9tcHRfY29tcGFyYXRpdmUoCiAgICAgICAgICAgIGFuYWx5emUsCiAgICAgICAgICAgIHByaW5jaXBsZT0oCiAgICAgICAgICAgICAgICAiYHZlcmlmaWVkYCBtdXN0IGJlIGV4YWN0bHkgdGhlIHNhbWUuIGBjb25maWRlbmNlYCBzaG91bGQgYmUgd2l0aGluICIKICAgICAgICAgICAgICAgICIxNSBwb2ludHMgb2YgZWFjaCBvdGhlci4gYHJlYXNvbmluZ2AgbWF5IGRpZmZlciBpbiB3b3JkaW5nIGJ1dCBzaG91bGQgIgogICAgICAgICAgICAgICAgInJlZmVyZW5jZSBzaW1pbGFyIGV2aWRlbmNlLiIKICAgICAgICAgICAgKSwKICAgICAgICApCgogICAgICAgIG5vdyA9IGludChkYXRldGltZS5ub3codGltZXpvbmUudXRjKS50aW1lc3RhbXAoKSkKICAgICAgICBzZWxmLnZlcmlmaWNhdGlvbl9yZXN1bHQgPSBqc29uLmR1bXBzKHBhcnNlZCkKICAgICAgICBzZWxmLnN0YXR1cyA9ICJ2ZXJpZmllZCIgaWYgcGFyc2VkLmdldCgidmVyaWZpZWQiKSBlbHNlICJyZWplY3RlZCIKICAgICAgICBzZWxmLnZlcmlmaWVkX2F0ID0gbm93Cg=="


@gl.evm.contract_interface
class _Recipient:
    class View:
        pass

    class Write:
        pass


class TaskFactory(gl.Contract):
    tasks: DynArray[Address]
    escrow: TreeMap[Address, u256]
    escrow_released: TreeMap[Address, bool]
    task_count: u256

    def __init__(self):
        self.task_count = 0

    @gl.public.write.payable
    def create_task(
        self,
        title: str,
        category: str,
        category_other: str,
        priority: str,
        estimated_effort: str,
        description: str,
        criteria: str,
        submission_format: str,
        submission_format_other: str,
        reward_amount: int,
        deadline: int,
    ) -> str:
        expected_value = u256(reward_amount) * u256(10**18)
        assert gl.message.value == expected_value, "Sent value must equal reward_amount GEN (in atto-GEN)"

        creator = str(gl.message.sender_address)
        factory_address = str(gl.message.contract_address)
        verifier_code = base64.b64decode(TASK_VERIFIER_CODE_B64)

        addr = gl.deploy_contract(
            code=verifier_code,
            args=[
                creator,
                factory_address,
                title,
                category,
                category_other,
                priority,
                estimated_effort,
                description,
                criteria,
                submission_format,
                submission_format_other,
                reward_amount,
                deadline,
            ],
            salt_nonce=int(self.task_count) + 1,
            on="accepted",
        )

        self.tasks.append(addr)
        self.escrow[addr] = gl.message.value
        self.escrow_released[addr] = False
        self.task_count += 1
        return str(addr)

    @gl.public.write
    def release_funds(self, task_address: str) -> None:
        addr = Address(task_address)
        assert addr in self.escrow, "Unknown task"
        assert not self.escrow_released.get(addr, False), "Escrow already released"

        other = gl.get_contract_at(addr)
        state = other.view().get_task_state()

        status = state["status"]
        assert status in ("verified", "rejected", "cancelled", "expired"), \
            "Task has not reached a terminal state"

        if status in ("verified", "rejected"):
            verified_at = int(state["verified_at"])
            assert verified_at > 0, "No verification timestamp recorded"
            now = int(datetime.now(timezone.utc).timestamp())
            assert now >= verified_at + RELEASE_WINDOW_SECONDS, "24h dispute window still open"
            recipient = state["worker"] if status == "verified" else state["creator"]
        else:
            # Cancelled (pre-claim, creator-initiated) and expired (deadline passed
            # with nothing ever submitted) both refund the creator immediately -
            # there was never anything to dispute from either state.
            recipient = state["creator"]

        amount = self.escrow[addr]
        self.escrow_released[addr] = True
        _Recipient(Address(recipient)).emit_transfer(value=amount)

    @gl.public.view
    def get_all_tasks(self) -> list[str]:
        return [str(a) for a in self.tasks]

    @gl.public.view
    def get_task_count(self) -> int:
        return int(self.task_count)

    @gl.public.view
    def get_escrow_status(self, task_address: str) -> dict:
        addr = Address(task_address)
        return {
            "locked_amount": self.escrow.get(addr, u256(0)),
            "released": self.escrow_released.get(addr, False),
        }
